#!/bin/bash
#SBATCH --job-name=SLV_151_unw_1
#SBATCH -N 4
#SBATCH --ntasks-per-node=10
#SBATCH --time=7-00:00:00
#SBATCH --mail-type=begin,end,fail,requeue
#SBATCH --mail-user=svhww@mst.edu
#SBATCH --export=all
#SBATCH --out=Foundry-%j.out
#SBATCH --mem-per-cpu=20G


#(executables) (options) (parameters)
echo "this is a general submission script"
echo "I've submitted my first batch job successfully"

cd /mnt/stor/geob/jlmd9g/Sanaz/SLV/Orbit_151/run_files



parallel -j 20   < run_16_unwrap1

echo "_____________________________________"
echo "_____________________________________"
echo "_____________________________________"
echo "_____________________________________"
echo "_____________________________________"
echo "_____________________________________"
echo "final job finished"
echo "_____________________________________"
echo "_____________________________________"
echo "_____________________________________"
echo "_____________________________________"
echo "_____________________________________"
echo "_____________________________________"
